### PR TITLE
Initialize Netlify deployments and update site

### LINKED ISSUE #5: Update site
We've gotten a number of new members, and we need to change the status of old members.

These logos need to be added as members. 

tcr logo converted 1 1

mpc logo jpg not transparent
mpc logo hi-res transparent
[Bluhm Printable Logo.docx](https://github.com/datamade/data-collab-marketing/files/2853048/Bluhm.Printable.Logo.docx)

We need to add a section for "Founding members"
and move citytech and adler into that section

### PR DESCRIPTION
**Pull request by jeancochrane**
## Summary

- Initialize static site deployments with Netlify
- Update logos for new partners and move founding members to a new section

Closes #5 

## Demo

New logos section:

partners

## Testing instructions

- Visit the deploy preview: https://deploy-preview-6--chicagodatacollaborative.netlify.com/
- Confirm that everything looks good

### CODE REVIEW

**Comment by derekeder** [comment]
A few comments on the logos:

* let's add some padding to the images so they are not so bunched up together
* the Chicago Reporter logo is very high contrast compared to the others. I'd reduce it to a more grey color like the others

**Comment by fgregg** [comment]
1. can we change "partner" to "member"
2. put mccormick foundation into own section, maybe as "supported by"

**Comment by jeancochrane** [comment]
Pushed up those changes, which should be reflected on the deploy preview: https://deploy-preview-6--chicagodatacollaborative.netlify.com/

How's the new padding @derekeder? Still too tight?

**Comment by derekeder** [comment]
Looks good!

**Comment by jeancochrane** [comment]
@fgregg Does https://deploy-preview-6--chicagodatacollaborative.netlify.com/ look OK to merge?

**Comment by fgregg** [comment]
looks great!

**Pull request merged**
